### ISSUE TITLE
Research how Neuralink is building a neural lace

### ISSUE THREAD

**Issue by quinnliu** [WalnutiQ/Ws#356]
## Software Engineer, Infrastructure & Tooling
Neuralink is looking for experienced and motivated software engineers to build a wide array of internal tools and infrastructure in anticipation of a petabyte-scale neuroscience program. Projects include building out a web-based experiment management and control system; near-real-time processing on gigabit+ data streams via complex algorithms defined by other teams; developing company-wide diagnostics and metrics; and more.

- [x] Fluency in multiple major programming languages such as C++, Python, Ruby, or Scala
- Experience with functional and imperative styles, and strong and dynamic type systems
- [x] The ability to use tests, type safety, and other tools to produce highly reliable code
- Experience with distributed systems and a real-world understanding of the myriad ways the network can cause problems
- [x] Experience using version control systems like Git and working within a code review workflow
- [x] Familiarity with deploying software into a Linux environment; experience with 12-factor PaaSes such as Heroku a plus.
- Knowledge of a range of database and message queue technologies like 
   - [x] PostgresSQL
   - Redis
   - MongoDB
   - Neo4J
   - [x] RabbitMQ
   - ZeroMQ
   - and their tradeoffs.

**Comment by quinnliu** [comment]
## Software Engineer, Embedded Systems & Firmware
Neuralink is looking for a experienced and motivated low-level software engineers. Projects you might work on include writing the code that runs "on head" mediating between the physical bio-device interface and the high level software interfaces, or writing low-level robotics control software to drive sophisticated novel neurosurgical robotics, among many other possibilities.

- Experience with ARM, x86, assembly, system BIOS and hardware/software integration
- Experience in firmware and device drivers development
- [x] Programming experience on Linux in Python, C, C++, Verilog, or VHDL.
- Familiarity setting up embedded tool chains, build, and debugging environments
- Experience with Wi-Fi, BLE, USB, TCP/IP stacks in an embedded environment

**Comment by quinnliu** [comment]
## Lab Technician
- Applied once

Neuralink is seeking a lab technician with close attention to detail and excellent fine motor skills. Experience with experience stereo-microscope aided microassembly is a strong plus. Some basic chemistry and biology experience requested, but training will be provided. It is expected that the ideal candidate will interface with the greater biomedical team, with open options for contributing to device and process development.

- [x] Excellent fine motor skills; patience.
- [x] Diligence and care in following established protocols
- Experience in a wet lab or microscopy-heavy lab environment
- Basic biology and chemistry (inorganic and organic)

**Comment by quinnliu** [comment]
# TODO
After considering all of the positions, I'm closest to, would most likely enjoy, and would be most useful as a Software Engineer, Medical Imaging

## Software Engineer, Medical Imaging
- Applied once

Neuralink is seeking a creative and motivated engineer to develop novel multi-modal medical imaging software suite for planning and control of a high-precision medical robotics. The engineer will work in an interactive, highly multidisciplinary team across neuroscience, medical devices, and materials science/microengineered systems, and is expected to contribute and learn in multiple domains.

Make a video about:
- [ ] integrating, using, and extending modern medical imaging software libraries
- [ ] algorithmic development skills: 
   - [x] segmentation
   - [ ] registration [coursera course on image registration](https://www.coursera.org/learn/neurohacking)
   - [ ] warping 
   - [ ] artifact correction 
   - [ ] path optimization
- [ ] strong awareness of imaging physics and fundamentals, including 
   - [ ] MR 
   - [ ] CT 
   - [ ] OCT
   - [ ] DIC, etc.
- [ ] working knowledge of robotics essential; ability to tightly integrate with low-level motor-control and constraint avoidance strong plus
- [x] proven record of delivering and refining high-reliability code, including unit testing, type safety, code documentation, and code instrumentation

**Comment by quinnliu** [comment]
### Maybe useful courses
- which modern medical imaging software libraries can I extend?
- [Image and Video Processing Cousera course](https://www.coursera.org/learn/image-processing/home/welcome)
- [edX MIT Underactuated Robotics](https://www.edx.org/course/underactuated-robotics-mitx-6-832x-0)
- [edX course about physics of biomedical imaging](https://courses.edx.org/courses/course-v1:UQx+BIOIMG101x+3T2016/info)

**Comment by quinnliu** [comment]
### Definition of words I don't know
- image segmentation = In computer vision, image segmentation is the process of partitioning a digital image into multiple segments
- image registration = Image registration is the process of transforming different sets of data into one coordinate system. 
   + [coursera course on image registration](https://www.coursera.org/learn/neurohacking)
- image warping = Image warping is the process of digitally manipulating an image such that any shapes portrayed in the image have been significantly distorted. <b>what for?</b>
- image artifact correction = PURPOSE: Image quality in computed tomography (CT) often suffers from artifacts which may reduce the diagnostic value of the image. ... The obtained projection data are used to reconstruct the corrected image.
- Computed tomography (CT) = an imaging procedure that uses special x-ray equipment to create detailed pictures, or scans, of areas inside the body. It is also called computerized tomography and computerized axial tomography (CAT).
- path optimization = In graph theory, the shortest path problem is the problem of finding a path between two vertices (or nodes) in a graph such that the sum of the weights of its constituent edges is minimized. [wiki](https://en.wikipedia.org/wiki/Shortest_path_problem)
